src/main/webui/src/technicalGoals/table.row.tsx

resolves #9 by populating the handle clone function within the technicalGoals/table.row.tsx. 
Also added some basic docs that helped assist myself in seeing the separate blocks of code. I do wonder if its possible to separate these out, so that they are not embedded within the main function, but left for a future optimisation.

resolves #9 (the failure to clone a technical goal)

---

src/main/webui/src/commonButtons/buttonInterfaceProps.tsx
src/main/webui/src/commonButtons/navigation.tsx
src/main/webui/src/observations/observationPanel.tsx

resolves #57 by doing the following:
1. creating a navigation button which handles routing to different parts of the UI. includes a parameterised icon, so could be the start for a generalised button code.
2. called hook for technical goals.
3. separated out the elements of the html in to functions, to try to make the html easier to read, and the fact that there is now a lot of ifs which would make the html even more nosier. these separations are:
1. the header, 2. the table generator, 3. a technical goal button, 4. a target button, 
5. reduced the error code detection to present all errors, not just the first one found.
6. separated out the loading logic so its in one place. If its loading, it no longer presents the table, as clearly this is noise.
7. generated html for the 3 invalid …

resolves #57 (locking out observations till targets and technical goals exist)

---

src/main/webui/src/observations/edit.group.tsx
src/main/webui/src/observations/timingWindowApi.tsx

Fixes issue #59.
- added 'TimingWindowApi' type to its own file in  the observations directory
- 'TimingWindowGui' converted to 'TimingWindowApi' when saving to the database

add ability to store timing windows on creation of a new observation

---

src/main/webui/src/commonButtons/buttonInterfaceProps.tsx
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/generated/proposalToolSchemas.ts
src/main/webui/src/observations/edit.group.tsx
src/main/webui/src/observations/edit.modal.tsx
src/main/webui/src/observations/observationPanel.tsx
src/main/webui/src/observations/observationTable.tsx
src/main/webui/src/observations/targetType.form.tsx
src/main/webui/src/observations/timingWindowApi.tsx
src/main/webui/src/observations/timingWindowGui.tsx
src/main/webui/src/observations/timingWindows.form.tsx

- add, edit and delete TimingWindows in existing Observations
- able to change the Target and TechnicalGoal in existing Observations
- disable the "Observation type" Select input for an existing Observation 
- use DateProvider around DateTimePickers to use timezone: UTC
- justify "centre" the "Add" new observation and the "Add" new timing window buttons 
New Issues:
- On changing the target of an existing Observation i.e., selecting a new target id and pressing "Save", the "view/edit" modal closes; it shouldn't do that and I don't know why it does. Editing any other value does not close the modal as programmed. 
- There's no API call to update the "intended use" of a Calibration Observation.

Djw 20 add edit delete timing windows existing observations

---

src/main/webui/src/App2.tsx
src/main/webui/src/main.tsx

That was a journey for something relatively simple. Turns out trying to use nested maps has issues. Anyway, NavLinks for proposals now reside in an Accordion and will be highlighted when selected. 
I have also fixed the scroll-ability issue. It looks like the 'Grid' element was blocking the scrollable functionality of the 'AppShell.Section'.

105 focus ring on navbar items is clipped

---

src/main/webui/src/targets/New.tsx
src/main/webui/src/targets/TargetTable.tsx

Stops a GUI user from adding two targets with identical names to the same proposal.
Name checking is case sensitive as that's what the API currently does when you request a named target on a given proposal.
The check is partly integrated into the form validation, so when a duplicate name is submitted the form is invalidated until the source name is changed.

99 duplicate targets

---

src/main/webui/Add_@types.patch
src/main/webui/src/App2.tsx
src/main/webui/src/ProposalManagerView/TAC/CommitteeMembers.tsx
src/main/webui/src/ProposalManagerView/TAC/tacPanel.tsx
src/main/webui/src/ProposalManagerView/allocations/allocationsPanel.tsx
src/main/webui/src/ProposalManagerView/availableResources/availableResourcesPanel.tsx
src/main/webui/src/ProposalManagerView/cycleList.tsx
src/main/webui/src/ProposalManagerView/observingModes/observingModesPanel.tsx
src/main/webui/src/ProposalManagerView/proposalCycle.new.form.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/Overview.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/dates.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/observatory.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/overview.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/possibleGrades.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/title.tsx
src/main/webui/src/ProposalManagerView/reviewers/List.tsx
src/main/webui/src/ProposalManagerView/reviews/reviewsPanel.tsx
src/main/webui/src/ProposalManagerView/startPage.tsx
src/main/webui/src/generated/proposalToolSchemas.ts

- Lists all ProposalCycles in the data base, and provides Navlinks to various sub-fields of a Cycle (content is mostly placeholder stuff)
- Added ability to create a new proposal cycle with the minimum amount of data. 
- updated proposalSchemas reflecting a change in the underlying data model, and to add missing fields for ProposalCycles and Observatories (patch file also updated).

122 manager view create proposal cycles

---

src/main/webui/src/ProposalEditorView/Investigators/List.tsx
src/main/webui/src/ProposalEditorView/Investigators/New.tsx
src/main/webui/src/ProposalEditorView/justifications/JustificationsPanel.tsx
src/main/webui/src/ProposalEditorView/observations/observationPanel.tsx
src/main/webui/src/ProposalEditorView/proposal/Documents.tsx
src/main/webui/src/ProposalEditorView/proposal/New.tsx
src/main/webui/src/ProposalEditorView/proposal/Submit.tsx
src/main/webui/src/ProposalEditorView/proposal/Summary.tsx
src/main/webui/src/ProposalEditorView/proposal/Title.tsx
src/main/webui/src/ProposalEditorView/proposal/ValidationOverview.tsx
src/main/webui/src/ProposalEditorView/targets/targetPanel.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/technicalGoalsPanel.tsx
src/main/webui/src/ProposalManagerView/TAC/tacNewMember.tsx
src/main/webui/src/ProposalManagerView/TAC/tacPanel.tsx
src/main/webui/src/ProposalManagerView/allocations/allocationsPanel.tsx
src/main/webui/src/ProposalManagerView/availableResources/availableResourcesPanel.tsx
src/main/webui/src/ProposalManagerView/observingModes/observingModesPanel.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/dates.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/observatory.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/possibleGrades.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/title.tsx
src/main/webui/src/ProposalManagerView/reviews/reviewsPanel.tsx
src/main/webui/src/commonPanelFeatures/panelFeatureInterfaceProps.tsx
src/main/webui/src/commonPanelFeatures/title.tsx

All panel titles are now run through a common render function.  This can be called directly or via a wrapper function that will get the proposal or cycle title from the API first.
This has made some code redundant where we queried for titles in panels, so I've cleaned this up where appropriate.

135 standardise panel titles

---

src/main/webui/src/App2.tsx
src/main/webui/src/ProposalManagerView/cycleList.tsx
src/main/webui/src/ProposalManagerView/proposalCycle.new.form.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/TACMembersTable.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/allocationGradesTable.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/availableResourcesTable.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/overview.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/possibleGrades.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/submittedProposalsTable.tsx

Added possible allocation grades, tac members, submitted proposals and available resources tables to the overview panel of a proposal cycle. This also removes possible allocation grades has an editable entity.

126 manager view display possible allocationgrades

---

src/main/webui/src/ProposalEditorView/investigators/List.tsx
src/main/webui/src/ProposalEditorView/investigators/New.tsx
src/main/webui/src/ProposalEditorView/justifications/justification.form.tsx
src/main/webui/src/ProposalEditorView/observations/edit.group.tsx
src/main/webui/src/ProposalEditorView/proposal/Documents.tsx
src/main/webui/src/ProposalEditorView/proposal/New.tsx
src/main/webui/src/ProposalEditorView/proposal/Submit.tsx
src/main/webui/src/ProposalEditorView/proposal/Summary.tsx
src/main/webui/src/ProposalEditorView/proposal/Title.tsx
src/main/webui/src/ProposalEditorView/targets/New.tsx
src/main/webui/src/ProposalEditorView/targets/targetPanel.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/edit.group.tsx
src/main/webui/src/ProposalManagerView/TAC/tacNewMember.tsx
src/main/webui/src/ProposalManagerView/TAC/tacPanel.tsx
src/main/webui/src/ProposalManagerView/availableResources/availableResources.form.tsx
src/main/webui/src/ProposalManagerView/availableResources/resourceType.form.tsx
src/main/webui/src/ProposalManagerView/proposalCycle.new.form.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/dates.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/observatory.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/title.tsx
src/main/webui/src/commonButtons/buttonInterfaceProps.tsx
src/main/webui/src/commonButtons/save.tsx
src/main/webui/src/commonPanel/appearance.tsx

Implemented a new button for some forms that automatically changes its tool tip and enable/disable state depending on if the form is dirty and or valid.
I've used this to harmonise some of the forms, they're not all laid out the same yet, but this goes quite some way to improve on what we had.  
This pull request contains a lot of changes, they're mostly minor, but any feedback will be appreciated!

161 make clear why save-update-submit buttons are disabled

---

src/main/webui/src/ProposalEditorView/proposal/Submit.tsx
src/main/webui/src/ProposalEditorView/proposal/ValidationOverview.tsx

Changes to the submit proposal panel
* Validation status is now updated by the validation element
* Invalid proposal/cycle combinations cannot be submitted
This means proposals cannot be submitted to a cycle where the deadline has already passed as this is no longer a valid combination.
Please note this PR is dependant on an API change in [this PR](https://github.com/orppst/pst-api-service/pull/44).

221 submit proposal after deadline

---

src/main/webui/src/ProposalEditorView/investigators/New.tsx
src/main/webui/src/ProposalEditorView/justifications/justification.form.tsx
src/main/webui/src/ProposalEditorView/observationFields/observationFields.form.tsx
src/main/webui/src/ProposalEditorView/observations/edit.group.tsx
src/main/webui/src/ProposalEditorView/proposal/Documents.tsx
src/main/webui/src/ProposalEditorView/proposal/New.tsx
src/main/webui/src/ProposalEditorView/proposal/Submit.tsx
src/main/webui/src/ProposalEditorView/proposal/Summary.tsx
src/main/webui/src/ProposalEditorView/proposal/Title.tsx
src/main/webui/src/ProposalEditorView/targets/New.tsx
src/main/webui/src/ProposalEditorView/targets/targetPanel.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/edit.group.tsx
src/main/webui/src/commonButtons/cancel.tsx

Previously was implemented as repurposed DeleteButton. So, created new CancelButton following Polaris standard in commonButtons with a more appropriate icon and called that where required. Ideally, would make handleCancel a single callable feature too...

Refine Cancel button

---

src/main/webui/src/ProposalEditorView/justifications/edit.modal.tsx
src/main/webui/src/ProposalEditorView/justifications/justification.form.tsx
src/main/webui/src/ProposalEditorView/justifications/justifications.table.tsx

Add defensive checks when trying to do stuff with a Justification text strings, that are supposed to be the empty string but seemingly identify as null/undefined after being fetched from the api.

Empty string showing as null or undefined

---

src/main/webui/src/ProposalEditorView/observations/edit.group.tsx
src/main/webui/src/ProposalEditorView/observations/observationPanel.tsx
src/main/webui/src/ProposalEditorView/observations/observationTable.tsx
src/main/webui/src/ProposalEditorView/observations/targetType.form.tsx
src/main/webui/src/ProposalEditorView/targets/TargetTable.tsx
src/main/webui/src/ProposalEditorView/targets/targetProps.tsx

Finish the GUI functionality to support multiple targets per observation.  Should also fix any errors that were happening when adding and editing observations.

231 save observation not working

---

src/main/webui/public/contextualHelpMessages.jsx
src/main/webui/src/ProposalEditorView/observationFields/ObservationFieldsPanel.tsx
src/main/webui/src/ProposalEditorView/observationFields/observationFields.form.tsx
src/main/webui/src/ProposalEditorView/observationFields/observationFieldsTable.tsx

This assigns a default / suggested name to new fields taking the form of "Field" plus an ordinal number given how many fields already exist.
It also blocks duplicate names, and the contextual help is updated to say field names are unique.

219 observation fields duplicates

---

.github/workflows/gradle.yml
src/main/webui/package-lock.json
src/main/webui/package.json
src/main/webui/src/ProposalEditorView/targets/New.tsx
src/main/webui/src/ProposalEditorView/targets/TargetTable.tsx
src/main/webui/tsconfig.json
src/main/webui/tsconfig.node.json

implemented sexagesimal unit for data entry and management of target name

175 - call for sexagesimal units in radial/decimal entry points

---

src/main/webui/src/App2.tsx
src/main/webui/src/ProposalEditorView/proposal/Overview.tsx
src/main/webui/src/commonButtons/delete.tsx
src/main/webui/src/commonButtons/export.tsx
src/main/webui/src/commonButtons/save.tsx

I've added a delete proposal button to the Overview Panel. 
I've included some layout and style changes for that page, and added an "export" common button. 
I've had to add a hack to force an App re-render after a proposal deletion. This is to avoid an issue where the recently deleted proposal still displays in the left-hand navbar despite having been removed from the database.

Delete proposal in Overview Panel

---

src/main/webui/src/App2.tsx
src/main/webui/src/ProposalEditorView/investigators/List.tsx
src/main/webui/src/commonButtons/swapRole.tsx
src/main/webui/src/main.tsx
src/main/webui/src/util/Modal.tsx

A refined workflow of modals to support management of investigators on proposal

Workflow to prevent deletion or removal of last PI

---

src/main/webui/src/ProposalEditorView/proposal/Overview.tsx
src/main/webui/src/commonButtons/export.tsx

Button added to proposal overview to clone the current proposal into a new one.

Clone functionality now in GUI

---

src/main/webui/src/ProposalEditorView/proposal/TitleSummaryKind.tsx
src/main/webui/src/commonButtons/buttonInterfaceProps.tsx
src/main/webui/src/commonButtons/save.tsx

Changed the form for title, summary, and kind such that edits to those things now occurs using the mutation functions rather than the "fetch" functions of the generated code.
I have also change the way these things are saved:
- The Title is updated via modifying the text then clicking the "Update Title" button (this avoids having to deal with blank titles if we'd use a debounce instead);
- The Summary uses a debounce function to save the text after the user has paused typing - note then that a summary may be blank but this could be something detected by server side validation before submission;
- The Kind is saved on change.
I have made this clear by adding descriptions to each input. I have also added optional customisable tool tip labels for when the "Update Title" button is disabled …

297 title, summary, and kind now use mutations 

---

src/main/webui/src/ProposalEditorView/justifications/JustificationsPanel.tsx
src/main/webui/src/ProposalEditorView/justifications/edit.modal.tsx
src/main/webui/src/ProposalEditorView/justifications/justification.form.tsx
src/main/webui/src/ProposalEditorView/justifications/justifications.table.tsx

Functions have been changed from 'fetch' to 'mutations'. Notice that this has significantly reduced the complexity of the code and removed the visual "twitch" when switching justification formats.

change 'fetch' calls to 'mutation' calls to update justifications

---

src/main/webui/src/ProposalEditorView/landingPage/proposalsAccordion.tsx
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/generated/proposalToolSchemas.ts

I got distracted and did this on the branch I used for justifications. 
Anyway, Landing page now uses a mutation call to withdraw a previously submitted proposal. I had to make a change to the API as the withdrawal call was wrongly annotated with 'GET' causing the code generator to create a query hook for the withdrawal function in typescript. I've changed it to 'DELETE' such that the code generator produces a mutation hook instead.

Landing page withdraw submitted proposal now uses mutation

---

src/main/webui/src/ProposalEditorView/observationFields/observationFields.form.tsx
src/main/webui/src/ProposalEditorView/observationFields/observationFieldsTable.tsx
src/main/webui/src/ProposalEditorView/observations/edit.group.tsx
src/main/webui/src/ProposalEditorView/observations/observationTable.tsx
src/main/webui/src/ProposalEditorView/observations/targetType.form.tsx
src/main/webui/src/ProposalEditorView/observations/timingWindows.form.tsx
src/main/webui/src/queryKeyProposals.tsx

The observations now use mutations to create, delete, and edit observations in the app. I've also done the same for observation fields. In the process I've also made a convenience function to return specific query keys for proposals, and used this when invalidating queries for observations.

318 observations change to mutations

---

src/main/webui/public/contextualHelpMessages.jsx
src/main/webui/src/App2.tsx
src/main/webui/src/ProposalEditorView/proposal/Documents.tsx
src/main/webui/src/ProposalEditorView/proposal/New.tsx
src/main/webui/src/ProposalEditorView/proposal/Overview.tsx
src/main/webui/src/ProposalEditorView/proposal/UploadProposal.tsx
src/main/webui/src/ProposalEditorView/proposal/downloadProposal.tsx
src/main/webui/src/commonButtons/contextualHelp.tsx

This has been done where possible. The 'downloadProposal' and 'uploadProposal' functions are designed to use promises and as such would need a significant redesign to use mutations. Instead, I have obtained the bearer's auth token at a higher level and passed it to the relevant functions to use in the 'header' part of the 'fetch' calls.

324 change remaining functionality in proposal to mutations

---

src/main/webui/Add_@types.patch
src/main/webui/src/ProposalEditorView/landingPage/proposalsAccordion.tsx
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/generated/proposalToolSchemas.ts

Change submitted proposal list to match by source proposalID, display multiple submissions to the same cycle where they exist.  Allow any of these to be withdrawn individually.
Please note that when starting from scratch the example proposal will no longer show as submitted to either cycle.  This is because the model example does not populate the related proposal composition after submitting.  Yes, this caught me out and had me confused for some time!  Any proposal submitted using the GUI (and thus the API) will appear in the list.

Show multiple submissions of the same source proposal to the same observing cycle

---

src/main/webui/src/ProposalEditorView/observations/timingWindows.form.tsx

Applied some additional logic to the `minDate` and `maxDate` fields on the `DateTimePicker`

Don't allow endTime < startTime or startTime > endTime in timing windows

---

src/main/webui/src/App2.tsx
src/main/webui/src/ProposalEditorView/targets/New.tsx
src/main/webui/src/ProposalEditorView/targets/TargetDecInput.tsx
src/main/webui/src/ProposalEditorView/targets/TargetRaInput.tsx
src/main/webui/src/ProposalEditorView/targets/TargetTable.tsx
src/main/webui/src/ProposalEditorView/targets/aladinTypes.tsx
src/main/webui/src/ProposalEditorView/targets/simbadSearch.tsx
src/main/webui/src/ProposalEditorView/targets/simbadSearchHelp.tsx
src/main/webui/src/ProposalEditorView/targets/targetPanel.tsx

- Moved new target form into a page panel
- adjusted the layout due to more space plus some responsiveness improvements
- more stringent format checking of the Ra and Dec inputs
- range checks added to both Ra and Dec inputs
- form submit button enabled only if all inputs are valid
- double click on the atlas viewer now populates Ra and Dec inputs with the viewer's central location directly
Couple of points about the Astrolib library functions: 
1. If a sexagesimal number contains no fractional part then Astrolib appears to not to understand that this is semantically the same as "ss.0" and does not perform a conversion to decimal degrees (for both RA and Dec). In this case, we can simply check for no decimal place in the sexagesimal string in the Typescript and append the ".0" where …

369 reformat add target to use page instead of modal

---

src/main/webui/public/contextualHelpMessages.jsx
src/main/webui/src/App2.tsx
src/main/webui/src/ProposalEditorView/observationFields/ObservationFieldsPanel.tsx
src/main/webui/src/ProposalEditorView/observations/edit.group.tsx
src/main/webui/src/ProposalEditorView/observations/edit.modal.tsx
src/main/webui/src/ProposalEditorView/observations/observationPanel.tsx
src/main/webui/src/ProposalEditorView/observations/observationTable.tsx
src/main/webui/src/ProposalEditorView/observations/targetType.form.tsx
src/main/webui/src/ProposalEditorView/targets/TargetTable.tsx
src/main/webui/src/ProposalEditorView/targets/targetProps.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/technicalGoalTable.tsx
src/main/webui/src/ProposalList.tsx
src/main/webui/src/commonButtons/buttonInterfaceProps.tsx
src/main/webui/src/commonButtons/save.tsx
src/main/webui/src/constants.tsx

User no longer has to create a TargetField, these are automatically created when an Observation is created. The TargetField is given the name of the (primary) target of the observation. 
Notice that I have made some visual changes to the Observation form with the intention to make it more user friendly. Also, a user must now provide at least one Timing Window to save an Observation.

373 make observation fields invisible to user

---

src/main/webui/package-lock.json
src/main/webui/package.json
src/main/webui/src/App2.tsx
src/main/webui/src/auth/Roles.tsx

Created a new function to test for a user's role(s) and used this to hide the management button from anyone who isn't a tac_admin or tac_member.
This does not stop a user pasting the management url into a browser to visit the page.  Further restrictions should be added in future.

371 restrict management page

---

src/main/webui/public/contextualHelpMessages.jsx
src/main/webui/src/ProposalEditorView/observations/edit.group.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/edit.group.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/edit.modal.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/performance.form.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/spectrum.form.tsx

Removed badge claiming work in progress for spectral line lookup service.
Performance Parameters and Spectral Windows now in their own tabs.
Update contextual help text. 
Notify users on successful edit to spectral windows.
(fixed problem with cancel buttons on modals, navigating "up-one" rather than just closing the modal)

378 remove badge re spectral line lookup plus tidy up

---

src/main/webui/src/ProposalEditorView/justifications/justifications.latex.tsx

Due to the way the page works it is simpler to pass the auth-token to the 'fetch' calls than change them to mutations.

fix authorisation issues on Justifications

---

src/main/webui/src/ProposalManagerView/assignReviewers/AssignReviewersPanel.tsx
src/main/webui/src/ProposalManagerView/assignReviewers/assignReviewers.accordion.tsx

Removed badge about tac-chair functionality.
Added badge when there are no remaining submitted proposals to assign reviewers.

Manager View: assign reviewers tidy up

---

src/main/webui/src/App2.tsx
src/main/webui/src/ProposalEditorView/investigators/New.tsx
src/main/webui/src/ProposalEditorView/proposal/Overview.tsx
src/main/webui/src/ProposalEditorView/proposal/UploadProposal.tsx
src/main/webui/src/ProposalEditorView/proposal/downloadProposal.tsx
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/util/telescopeComms.tsx

added code to call the rest api for the telescope timing data and then using it within the overview summary code to calculate hours. 
it also includes a number of fixes to importing proposals which were found during a demo. Now the investigators of imported proposals are checked and if the current user doesnt exist in the list, it is added. any other missing users are removed as well. includes a fix to the export as well so that the optical files are ensured to exist. as a export failed randomly and so we found a race condition which needed shutting down

409 abs nights vs hours

---

src/main/webui/src/App2.tsx
src/main/webui/src/ProposalManagerView/cycleList.tsx
src/main/webui/src/ProposalManagerView/proposalCycle.new.form.tsx
src/main/webui/src/ProposalManagerView/startPage.tsx

I've changed the TAC management page, mostly just the left hand menu.  I believe it makes more sense this way.
By default it lists all cycles that you are associated with.  These can be filtered to show only those that are still open for submissions, and optionally filtered by observatory.  The observatory filter has been moved to the left hand menu and is only shown when the option is selected, this fixes the initial render issue.

Move and fix filter cycles by observatory

---

src/main/webui/src/App2.tsx
src/main/webui/src/ColourSchemeToggle.tsx
src/main/webui/src/ProposalEditorView/targets/TargetTable.tsx
src/main/webui/src/ProposalManagerView/startPage.tsx
src/main/webui/src/admin/adminPanel.tsx
src/main/webui/src/commonButtons/buttonInterfaceProps.tsx
src/main/webui/src/commonButtons/save.tsx
src/main/webui/src/commonButtons/undo.tsx
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/userManagement.tsx
src/main/webui/src/userMenu.tsx
src/main/webui/src/userResetPassword.tsx

Added a "user profile" page to the app where users can update their first and last names, email address, home institute, orchid id, and reset their password. I've implemented a password validator that has several requirements to create a "strong" password.
This also includes a tidy up of the top bar of the app to use a "user menu" that contains a navigation button to the "user profile" page, and the logout button.  This allows for future, additional stuff to be included in that menu.
I've also change the name of the button that navigates to the landing page or as we now call it the user's "home page".

419 user management required

---

src/main/webui/src/ProposalEditorView/submitProposal/ValidationOverview.tsx
src/main/webui/src/ProposalEditorView/submitProposal/observationModeDetailsShow.tsx
src/main/webui/src/ProposalEditorView/submitProposal/submission.form.tsx

Added logic to prevent a proposal with no observations being allowed to submit to a proposal cycle (thinking about it, this should also be prevented in the API).
I've also made some functional tweaks, such as disabling the "Next Step" button when no cycle is selected, if the proposal does not pass the basic checks, and if the user has not selected observing modes for all their observations. This includes adding relevant tool-tip messages for the "Next Step" button.
Additionally, I have included visual tweak to the validation messages being displayed in different colours depending on their "severity": green for okay, orange for warnings, red for errors.

429 an invalid proposal may be submitted

---

src/main/webui/Add_@types.patch
src/main/webui/src/ProposalEditorView/landingPage/observatoriesCycles.tsx
src/main/webui/src/ProposalEditorView/submitProposal/ValidationOverview.tsx
src/main/webui/src/ProposalEditorView/submitProposal/displaySubmissionDetails.tsx
src/main/webui/src/ProposalManagerView/allocations/allocationsPanel.tsx
src/main/webui/src/ProposalManagerView/landingPage/tacCycles.tsx
src/main/webui/src/ProposalManagerView/proposalCycle/details.tsx
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/generated/proposalToolSchemas.ts

Move proposal cycle code into the same endpoint as dates, now called details and returns a ProposalCycleSynopsis object. All updates on the details panel are now in a single API call.
Important: This is codependent on the same branch being released to pst-lib and pst-api-service

ARE aggregate cycle details
