orppst/pst-gui

src/main/webui/src/technicalGoals/Goals.tsx
src/main/webui/src/technicalGoals/table.row.tsx

supersedes: https://github.com/orppst/pst-gui/pull/16

resolves #15 (the issue with units in the technical goals table). 

---

src/main/webui/src/App2.tsx

resolves #14 by changing the relative path to a root based path. So far this seems to fix the problem.
main change is on line 152, the rest of the changes are bringing the file into 80 char column width.
It seems to have fixed it, but given how unreliable it was to find the bug, I'm not 100% sure its fixed. only time will tell.

resolves #14 by changing the realtive path to a root based path

---

src/main/webui/src/commonInputs/NumberInputPlusUnit.tsx
src/main/webui/src/technicalGoals/edit.group.tsx
src/main/webui/src/technicalGoals/edit.modal.tsx
src/main/webui/src/technicalGoals/performance.form.tsx
src/main/webui/src/technicalGoals/render.technicalGoal.tsx
src/main/webui/src/technicalGoals/scienceSpectralWindowGui.tsx
src/main/webui/src/technicalGoals/spectrum.form.tsx
src/main/webui/src/technicalGoals/technicalGoalTable.tsx
src/main/webui/src/technicalGoals/technicalGoalsPanel.tsx

contains loads of doc changes.
Also includes a few inlines which the IDE found.
please merge into https://github.com/orppst/pst-gui/pull/40/ before merging that one

docs missed

---

src/main/webui/src/targets/New.tsx

resolves #49 by doing the following:
1. separating out the submit functionality to the database into its own function.
2. doing a check on what the active field is (using ref objects) to determine if the enter commend should set off a simbad search, or a save to the database.
3. disables the save till the form is valid. 
4. to ensure the disable and search works correctly, 2 new fields were added to the form, searching and lastSearch. this allows the second enter (once a search is over) to trigger the database save, and that if the user changes the targets name between enters, it doesnt force a save. Annoyingly, it seem to ensure the button disable works correct, i had to put the fields in the form, otherwise it wouldnt detect the changes.

tries to resolve #49

---

src/main/webui/src/App2.tsx

resolves #5 requested in zoom meeting. made the block distinct with divider and background color. also doced the file and separated out functionality to allow future movements as needed.
note that a major redesign of this ui component is likely planned for down line from here.

resolves #5 as discussed within recent zoom meeting

---

src/main/webui/src/commonInputs/remainingCharacterCount.tsx
src/main/webui/src/proposal/New.tsx
src/main/webui/src/proposal/Summary.tsx
src/main/webui/src/proposal/Title.tsx

And a character counter from the the edit summary pane, and apply limit to new title and edit title.

Resolves #51 add string limits to create proposal

---

src/main/webui/src/generated/proposalToolSchemas.ts
src/main/webui/src/technicalGoals/edit.group.tsx
src/main/webui/src/technicalGoals/render.technicalGoal.tsx
src/main/webui/src/technicalGoals/scienceSpectralWindowGui.tsx
src/main/webui/src/technicalGoals/spectrum.form.tsx

Fixes #12.
- add a map of form spectral windows to convert to an appropriate type to save to the database

Store spectral windows on the creation of a new technical goal

---

Add_@types.patch
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/generated/proposalToolSchemas.ts

Have rebuilt the code gen files to reflect the latest proposal model, recreated and applied the patch file.
Should be easy to test by regenerating the code with 
`cd src/main/webui`
`yarn run gen` 
And apply the patch file
`patch -u src/generated/proposalToolSchemas.ts -i ../../../Add_@types.patch`
If it works, there should be no project typescript errors (and everything else should still work!)

Rebuild code gen files, rebuilt and applied patch file

---

src/main/webui/src/proposal/New.tsx

To quickly fix this problem, I've patched in a temporary field record.

Patch in a blank field on create new proposal

---

src/main/webui/src/constants.tsx
src/main/webui/src/proposal/UploadProposal.tsx
src/main/webui/src/proposal/downloadProposal.tsx

Don't import hidden files or overview pdf

---

src/main/webui/src/App2.tsx
src/main/webui/src/commonButtons/viewEdit.tsx
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/justifications/JustificationsPanel.tsx
src/main/webui/src/justifications/edit.modal.tsx
src/main/webui/src/justifications/justification.form.tsx
src/main/webui/src/justifications/justifications.table.tsx
src/main/webui/src/observations/observationPanel.tsx
src/main/webui/src/proposal/New.tsx
src/main/webui/src/technicalGoals/technicalGoalsPanel.tsx

User can now add justifications on creation of a proposal, and edit these afterwards in the 'Justifications' section of the proposal.

#100 add justifications

---

src/main/java/org/orph2020/pst/gui/auth/ProtectedResource.java
src/main/webui/Add_@types.patch
src/main/webui/src/auth/Auth.tsx
src/main/webui/src/auth/NewOrganization.tsx
src/main/webui/src/auth/NewUser.tsx
src/main/webui/src/generated/proposalToolSchemas.ts

New users now asked to select from known organisations, or to supply new organisation details if their institute is not known. The new user when registered successfully is assigned the UUID from KeyCloak. 
Notice that to get the newly added organisation into the selection list a 'location.reload()' is performed by getting the user to press an "okay" button in a secondary modal, after the new details have been submitted.

97 new user registration need affiliation

---

src/main/webui/src/targets/TargetTable.tsx
src/main/webui/src/technicalGoals/technicalGoalTable.tsx

Just adds row highlighting on target table and technical goals table

108 improve select targets and technical goals

---

src/main/webui/src/ProposalEditorView/justifications/justification.form.tsx
src/main/webui/src/constants.tsx

Added a new constant for the size of justifications and used this on the edit form.

New constant for max size of justification text

---

src/main/webui/src/ProposalEditorView/investigators/New.tsx
src/main/webui/src/ProposalEditorView/justifications/justification.form.tsx
src/main/webui/src/ProposalEditorView/observations/edit.group.tsx
src/main/webui/src/ProposalEditorView/proposal/New.tsx
src/main/webui/src/ProposalEditorView/targets/New.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/edit.group.tsx

To give a consistent style, Save buttons have been
--- relocated to bottom of form, and centred
--- labelled as Save throughout

Standardise save buttons in ProposalEditorView

---

src/main/webui/src/ProposalManagerView/allocations/allocatedBlocks.table.tsx

Delete button for allocated resource blocks now functional, protected with a confirm modal.

add delete functionality to allocated resource blocks

---

src/main/webui/src/ProposalEditorView/targets/New.tsx

For the prototype version we assume all targets are in ICRS and have an epoch of J2000. 
We can re-enable coordinate reference system and epoch selection in the overhaul of the SIMBAD integration #194

Assume ICRS and J2000 for all targets

---

src/main/webui/src/ProposalEditorView/proposal/Overview.tsx

Added // @ts-ignore to a line in const DisplayObservations to inhibit unexpected behaviour with Cancel button

temporary fix to proposal/Overview.tsx

---

src/main/webui/src/commonButtons/contextualHelp.tsx

small change to contextualHelp.tsx to follow Polaris theme

align help button theme with Polaris standard

---

src/main/webui/src/ProposalEditorView/proposal/New.tsx

fixed path in function handleCancel

Fix unhandled error when cancelling Create a new proposal

---

src/main/webui/src/ProposalEditorView/observations/observationTable.tsx

Return the main target name to the observations table, and add a new column of additional target count

Target name and additional targets column

---

src/main/webui/src/ProposalEditorView/proposal/Overview.tsx

On the proposal overview panel, change observation names to a list of their targets (max. 3)

246 multiple targets in multiple observations observations

---

src/main/webui/src/ProposalEditorView/investigators/New.tsx

When building the drop down search list to add a new investigator, anyone already assigned to the proposal is filtered out.
This does not restrict how many PIs or CO-Is a proposal can have.
Please note, the filtering is done by investigator's full name because the database id's of the returned lists do not match.  There is a _very_ small chance this will be a problem if two people with exactly the same name are in the system.  However, there's currently no way to distinguish between people with identical names in the GUI!

Remove existing investigators from search list on add new investigator

---

src/main/webui/src/ProposalEditorView/technicalGoals/performance.form.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/technicalGoalTable.tsx
src/main/webui/src/physicalUnits/PhysicalUnits.tsx

Desired sensitivity units changed to Janskys, with some appropriate metric prefixes. Can be easily added to.

Flux units of Janskys added

---

src/main/webui/src/ProposalEditorView/investigators/List.tsx
src/main/webui/src/ProposalEditorView/investigators/New.tsx

Refactor the investigator panels

297 mutations investigators

---

src/main/webui/src/ProposalEditorView/technicalGoals/edit.group.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/spectrum.form.tsx
src/main/webui/src/ProposalEditorView/technicalGoals/technicalGoalTable.tsx

Title describes it with sufficient accuracy

technical goals now use mutations instead of fetches

---

src/main/webui/src/ProposalEditorView/targets/New.tsx
src/main/webui/src/ProposalEditorView/targets/TargetTable.tsx

Also, I've changed the way target name uniqueness is checked and fed back to the user.

targets now use a mutation to add new targets

---

src/main/webui/src/ProposalManagerView/proposalCycle.new.form.tsx

Creating a cycle fails (for me), but this appears unrelated.

Changed to uses and mutations 

---

src/main/webui/src/ProposalManagerView/assignReviewers/assignReviewers.form.tsx

Assignment and removal of a reviewer to a submitted proposal now uses mutations instead of fetches.

assign reviewers now uses mutations

---

src/main/webui/src/ProposalManagerView/availableResources/availableResourcesPanel.tsx
src/main/webui/src/ProposalManagerView/availableResources/resourceType.form.tsx
src/main/webui/src/ProposalManagerView/availableResources/resourceType.modal.tsx

change to mutation to remove a cycle resource, delete the fetch 'get call for resource types - it was never accessed, add comment re: limitations of this code.

Available resource now use mutations

---

src/main/webui/src/ProposalManagerView/TAC/tacNewMember.tsx
src/main/webui/src/ProposalManagerView/TAC/tacPanel.tsx

Must use a 'fetch-get' call rather than a query as it involves user selectable input re: reviewer id.

change TAC page to use mutations where possible

---

src/main/webui/src/ProposalManagerView/proposalCycle.new.form.tsx

The observatory @type property changed from `proposal:Observatory` to `proposalManagement:Observatory`

323 create new proposal cycle fails

---

src/main/resources/orppst-realm.json

Client ID and secret must be obtained for this sandboxed version of ORCiD IdP to work correctly.

Updated ORPPST realm config including ORCiD IdP

---

src/main/webui/src/ProposalManagerView/allocations/allocatedBlocks.table.tsx

fix display bug for grade, observing mode, and resource type names

Use some object arrays to lookup object references

---

src/main/webui/src/ProposalEditorView/targets/New.tsx
src/main/webui/src/ProposalEditorView/targets/simbadSearch.tsx

Several updates that change the priority of RA and Dec input formats from Degrees to Sexagesimal coords.

Rework RA and Dec data entry, including update of Aladin behaviour

---

src/main/webui/src/ProposalEditorView/proposal/Documents.tsx

POST request was missing the auth bearer token

Add auth token to upload supporting document POST header

---

src/main/webui/src/App2.tsx
src/main/webui/src/ProposalEditorView/proposal/UploadProposal.tsx
src/main/webui/src/ProposalEditorView/proposal/downloadProposal.tsx
src/main/webui/src/constants.tsx
src/main/webui/src/generated/proposalToolComponents.ts
src/main/webui/src/generated/proposalToolContext.ts
src/main/webui/src/util/telescopeComms.tsx

adds import and export functionality to the optical telescopes.

356 abs optical import export

---

src/main/webui/src/ProposalEditorView/observationFields/observationFields.form.tsx
src/main/webui/src/ProposalEditorView/proposal/Overview.tsx
src/main/webui/src/ProposalEditorView/submitProposal/displaySubmissionDetails.tsx
src/main/webui/src/ProposalEditorView/submitProposal/submission.form.tsx
src/main/webui/src/generated/proposalToolContext.ts

removes the observation modes from the submission page when in optical mode. 
it also includes a quick fix for the maths for hours vs nights.

411 abs removes submission mode from the optical submission page.

---

src/main/webui/src/App2.tsx
src/main/webui/src/ProposalEditorView/justifications/justifications.help.tsx
src/main/webui/src/ProposalManagerView/startPage.tsx

'TAC Management' and 'Proposal Editor' added to buttons.
This also includes additions to justifications help, because why not.

Text added to navigator buttons between views
